import ItemsGrid from '@/components/Items/ItemsGrid';
import React from 'react'

export const metadata = {
  title: "All Items",
  description: "Generated by create next app",
};

async function getItems() {
  const res = await fetch(`${process.env.NEXTAUTH_URL}/api/items`, {
    cache: "no-store",
  });

  if (!res.ok) {
    throw new Error("Failed to fetch items");
  }

  return res.json();
}

export default async function ItemsPage() {
  const items = await getItems();

  return (
    <section className="min-h-screen bg-gradient-to-b from-slate-50 via-white to-slate-100">
      <div className="max-w-7xl mx-auto px-6 py-16">
        <h1 className="text-4xl font-bold mb-10 text-center">
          Explore Our Products
        </h1>

        <ItemsGrid items={items} />
      </div>
    </section>
  );
}