import React from 'react'

export const metadata = {
  title: "All Items",
  description: "Generated by create next app",
};

const ItemsPage = () => {
  return (
     <div className="max-w-7xl mx-auto px-6 py-16">
      <h1 className="text-3xl font-bold">Items Page</h1>
    </div>
  )
}
export default ItemsPage;